# R CODE FOR LAND COVER: 
# ANALISI DELLA COPERTURA DEL SUOLO (21/04/20)

setwd("C:/LAB")

library(raster)
library(RStoolbox)

p224r63_2011 <- brick("p224r63_2011_masked.grd")


# PLOT RGB
plotRGB(p224r63_2011, r=4, g=3, b=2, stretch="Lin")

# "unsuperClass(...)": CON QUESTO COMANDO, PROPRIO DI RStoolbox, DEVO SPECIFICARE IMMAGINI E N° CLASSI (IN MAIUSCOLO!)
# I PIXEL VENGONO ACCORPATI NELLE VARIE CLASSI/CLUSTER
               
p224r63_2011c <- unsuperClass(p224r63_2011, nClasses=4)

p224r63_2011c

plot(p224r63_2011c$map)
# FACCIO UN PLOT DELLA MAPPA LEGATA ALL'IMMAGINE CON "$"

clclass <- colorRampPalette(c('green', 'red', 'blue', 'black'))(100) 
plot(p224r63_2011c$map, col=clclass)
# LEGENDA: AD OGNI CLASSE (4) VIENE ASSOCIATO UN COLORE, VISUALIZZATO NELLA SCALA ALLA DESTRA DELL'IMMAGINE
                          
p224r63_2011c <- unsuperClass(p224r63_2011, nClasses=2) 
# STESSO PROCESSO CON MENO CLASSI (2)
  

# CONSIDERAZIONI FINALI:
                    
# DATE CLASSI DIFFERENTI, L'INCERTEZZA DELL'ALGORITMO AUTOMATICO DI CLASSIFICAZIONE AUMENTA IN FUNZIONE DEL N° CLASSI: 
# PER QUESTO SI PARLA DI SENSITIVITA' DELL'ALGORITMO
